### ISSUE TITLE
Support for gaps in AA identifiers

### ISSUE THREAD

**Issue by GJPvWesten** [cambDI/camb_old#23]
Guys, peraps it is good to add support for gaps in the AA descriptor calculation (this will probably be needed rather often).

One way you can do this is by adding the 0 descriptor for gapps (essentially create a unique class for gaps that is Z1 - 0 , Z2 - , Z3 - 0, Z4 - 0 , Z5 - 0)

Let me know what you think..

**Comment by isidroc** [comment]
In any case, you could calculate the descriptors for the fragments between gaps and then concatenate them..
Moreover, for some AA descriptors supported the 0 value might have a meaning different from NULL

**Comment by GJPvWesten** [comment]
Hi Isidro,

I don't want to be annoying, but if you use multiple sequence alignments, actually the gaps contain information. Moreover if you just discard them you loose information and CHANGE the alignment. Potentially ruining your model. 

I know for the a number of amino acid descriptors (at least all the ones in our J cheminf paper) , none of them have all 0 values for any amino acid. They have 0 values in some of the higher principal components (e.g. VHSE 5 for Cystein), but adding a full 0 value would create a 21st amino acid class in all. And I feel this is important to implement, as simply concatenating the values would effectively remove all value added by aligning the sequences. 

(note that this is not relevant if you use alignment independent descriptors). 

So, I would urge addition of support for '-' as gap. 

Cheers

**Comment by isidroc** [comment]
This is now implemented
