### ISSUE TITLE
Decide what we do with the impute package. Find alternative?

### ISSUE THREAD

**Issue by isidroc** [cambDI/camb_old#27]

**Comment by dsmurrell** [comment]
We could just wait and it will probably be accepted in the latest R version. If we wait too long though, we should find an alternative.

**Comment by isidroc** [comment]
We can install it from:
http://www.bioconductor.org/packages/release/bioc/html/impute.html

**Comment by isidroc** [comment]
I read that it is not easy to put a dependency corresponding to a package outside CRAN.
Now, the package is required when using the function, but it is not listed as a dependency.
We can leave it like that until we find out how to include the dependency from bioaconductor

**Comment by dsmurrell** [comment]
sounds good.

**Comment by isidroc** [comment]
another issue. How are we going to include the ensemble? With the same
functions as in caretEnsemble, or putting a wrap?
We could just add them to our package and ask Zach to see if he agrees.
Would be more convenient to avoid repetitions.. (stupid repetitions I mean)

2014-03-31 14:57 GMT+02:00 Daniel Murrell notifications@github.com:

**Comment by dsmurrell** [comment]
Yeah, he says that he doesn't mind what we do. We can just copy his R files
over and see if they work ok. You can assign that to me if you like.

**Comment by isidroc** [comment]
Ok, perfect, copying now
Then, we should ask him for co-authorship, right?

2014-03-31 15:04 GMT+02:00 Daniel Murrell notifications@github.com:

> Yeah, he says that he doesn't mind what we do. We can just copy his R files
> over and see if they work ok. You can assign that to me if you like.
>

**Comment by isidroc** [comment]
done

2014-03-31 15:10 GMT+02:00 Isidro Cortés isidrolauscher@gmail.com:

> Ok, perfect, copying now
> Then, we should ask him for co-authorship, right?
> 
> 2014-03-31 15:04 GMT+02:00 Daniel Murrell notifications@github.com:
> 
> Yeah, he says that he doesn't mind what we do. We can just copy his R files
> 
> > over and see if they work ok. You can assign that to me if you like.
> >

**Comment by isidroc** [comment]
so, just to make sure we do it. Are you writing to Zach, should I do it, or
did you already discussed that?

2014-03-31 15:14 GMT+02:00 Isidro Cortés isidrolauscher@gmail.com:
