### ISSUE TITLE
Check all these files are required in the COX example...

### ISSUE THREAD

**Issue by dsmurrell** [cambDI/camb_old#35]
https://www.dropbox.com/s/wbbo23d3et378ve/Screenshot%202014-04-01%2000.10.22.png

Here's a screenshot of the size distribution for the COX example... are all these files required? I'm just checking... they might be... but if some aren't or are generated in running the example we could remove them to save space.

**Comment by isidroc** [comment]
Once the knitter file is finalized, I will remove the unnecessary files.
