### ISSUE TITLE
Why does this funtion (and others) have a two dot parameter?

### ISSUE THREAD

**Issue by dsmurrell** [cambDI/camb_old#47]
AA_descs <- function(data, type="Z5", ..){

Is there a reason for this?

**Comment by isidroc** [comment]
Yes!!
Becuase like that you can pass more arguments!
In the case of e.g. "trainControl" anything you put will be read by the function called within the function. See here an example:

RemoveNearZeroVarianceFeatures <- function(ss, frequencyCutoff = 30/1,...) {
  nzv.columns <- nearZeroVar(ss$x.train, freqCut = frequencyCutoff,...)

If you pass more arguments to "RemoveNearZeroVarianceFeatures", they will be added where there are dots inside the function, namely: "nearZeroVar".

Am I clear enough?

The dots are totally necessary to allow the input of function arguments without the need to specify all of them in the function definition. Specially useful with functions such as preprocess, where the number of options is large.

**Comment by dsmurrell** [comment]
Ahh ok, I thought it was three dots? Am I mistaken?
