### ISSUE TITLE
Do you know what the R/functions file is there for??

### ISSUE THREAD

**Issue by dsmurrell** [cambDI/camb_old#49]
I have no idea what this is supposed to be doing.

**Comment by isidroc** [comment]
It is a list of the functions in the package.
If there is a \t, it indicates that the doc has already been written for it.
It was to keep track about the doc. Maybe useless now with the roxygen method..

**Comment by dsmurrell** [comment]
Ahh ok, makes sense... I'll look at it to see the status and then get rid
of it. You can assign this one to me.
