### ISSUE TITLE
What does the loadMorganFPs function do in Descriptors.R?

### ISSUE THREAD

**Issue by dsmurrell** [cambDI/camb_old#50]
I can't see where it's being called and it has no documentation so I assume it's not used externally, or is it?

**Comment by isidroc** [comment]
It was there to read the FPs, raising an error if the file does not exist.. 
However, this can be easily done with read.table (I) or read.csv (you) :-) 
So I guess we can remove it.

**Comment by dsmurrell** [comment]
Ok, cool, lets remove everything that we don't need anymore to make it as
clean as possible to maintain.
