### ISSUE TITLE
I'm not quite following this...

### ISSUE THREAD

**Issue by dsmurrell** [cambDI/camb_old#52]
![screenshot 2014-05-23 15 33 13](https://cloud.githubusercontent.com/assets/4035854/3067823/42c27928-e287-11e3-97ca-a77bda9901a5.png)

Maybe the output should be show here so that the user can see what is going on. It doesn't look like you are using these in your workflow. Since mine should be more of an introduction, would these functions be something that I should show in mine and then there is less bloat in yours? Can you modify them such that an output is shown and then I'll move them into mine?

**Comment by isidroc** [comment]
Ok, you can include them in your tutorial. I will remove them from mine as it is true I do not require them for my modelling.
The functions I will remove are: ShowPropertiesSDF and GetPropertySDF. 
In anny case, I do not think they are harmful either.. :-)
