### ISSUE TITLE
Discussion: can pairwise similary of compounds be described here?

### ISSUE THREAD

**Issue by dsmurrell** [cambDI/camb_old#8]

**Comment by isidroc** [comment]
Yes. The similarity of each compound (in the descriptor space) to all compounds is calculated.
Thus, a similarity matrix which dimensions are N X (N-1), where N is the number of compounds.
The diagonal (autosimilarity is not considered). Likewise, only one half of the matrix is considered.
Then, all values are depicted as an histogram. Clear?
